# == Schema Information
# Schema version: 20110227014344
#
# Table name: shifts
#
#  id              :integer(4)      not null, primary key
#  title           :string(255)     not null
#  description     :text
#  start           :time
#  end             :time
#  event_id        :integer(4)      not null
#  volunteer_count :integer(4)      default(1), not null
#  created_at      :datetime
#  updated_at      :datetime
#

class Shift < ActiveRecord::Base
  belongs_to :event
  
  has_many :registrations
  has_many :users, :through => :registrations
  
  def google_calendar_link
    # sample link generated by Google form at: http://www.google.com/googlecalendar/event_publisher_guide.html#individual
    #url = "http://www.google.com/calendar/event?action=TEMPLATE&text=Easter%20Meal&dates=20110424T140000Z/20110425T000000Z&details=Short%20Description&location=Veteran's%20Memorial%20Building&trp=false&sprop=http%3A%2F%2Fvolevent.heroku.com&sprop=name:VolEvent"
    text = URI.escape(self.title + " - " + self.event.name)
    dates = self.event.start_date.strftime("%Y%m%dT") + self.start.strftime("%H%M%S") + "/" + self.event.start_date.strftime("%Y%m%dT") + self.end.strftime("%H%M%S")
    details = URI.escape(self.description)
    loc = URI.escape(self.event.location.name)
    url = "http://www.google.com/calendar/event?action=TEMPLATE&text=#{text}&dates=#{dates}&details=#{details}&location=#{loc}&trp=false&sprop=http%3A%2F%2Fvolevent.heroku.com&sprop=name:VolEvent"
  end
  
  def volunteers
    users
  end
  
  def is_full?
    volunteers.count >= volunteer_count
  end
  
  def user_registration(user)
    registrations.find(user)
  end
end
